// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMzYKWs1KPR35WWL4whKWoeM0a66SpDy0',
    appId: '1:798986307031:web:18afa0d2ea1184b42db792',
    messagingSenderId: '798986307031',
    projectId: 'cmsc23-jdgadil',
    authDomain: 'cmsc23-jdgadil.firebaseapp.com',
    storageBucket: 'cmsc23-jdgadil.appspot.com',
    measurementId: 'G-0FER5PN03G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRJ8hdPrYKa6sdnBcoXXTSYutH4KBdFo',
    appId: '1:798986307031:android:21ea9d94892f75f22db792',
    messagingSenderId: '798986307031',
    projectId: 'cmsc23-jdgadil',
    storageBucket: 'cmsc23-jdgadil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTzVcFMzOCHt4ZZlnNUFT1uwmZ-NzvPc',
    appId: '1:798986307031:ios:649cfeb46db067462db792',
    messagingSenderId: '798986307031',
    projectId: 'cmsc23-jdgadil',
    storageBucket: 'cmsc23-jdgadil.appspot.com',
    iosClientId: '798986307031-5rbioqnikhi1uhsk5rsf76hma2ek7gsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTzVcFMzOCHt4ZZlnNUFT1uwmZ-NzvPc',
    appId: '1:798986307031:ios:649cfeb46db067462db792',
    messagingSenderId: '798986307031',
    projectId: 'cmsc23-jdgadil',
    storageBucket: 'cmsc23-jdgadil.appspot.com',
    iosClientId: '798986307031-5rbioqnikhi1uhsk5rsf76hma2ek7gsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
